format text

diff --git a/sh.ppy.Osu/sh.ppy.Osu.yml b/sh.ppy.Osu/sh.ppy.Osu.yml
--- a/sh.ppy.Osu/sh.ppy.Osu.yml
+++ b/sh.ppy.Osu/sh.ppy.Osu.yml
@@ -31,105 +31,102 @@ build-options:
     V: '1'
 
 modules:
-  - name: setup-wine
-    buildsystem: simple
-    build-commands:
-      - mkdir -p /app/wine
+- name: setup-wine
+  buildsystem: simple
+  build-commands:
+  - mkdir -p /app/wine
 
+- name: wine-win32
+  config-opts:
+  - --disable-win64
+  - --disable-win16
+  - --disable-tests
+  - --with-x
+  - --with-ldap
+  - --with-netapi
+  - --without-cups
+  - --without-curses
+  - --without-capi
+  - --without-glu
+  - --without-gphoto
+  - --without-gsm
+  - --without-hal
+  - --without-opencl
+  - --without-pcap
+  - --without-udev
+  cleanup:
+  - /app/wine/app/wine/share/man
+  - /app/wine/share/applications
+  sources:
+  - type: archive
+    url: https://dl.winehq.org/wine/source/3.x/wine-3.18.tar.xz
+    sha256: 9be8d44b1b22814c76e6214fe8ce657ae90a7a17879e5cd2b2a87ad6a1391a77
 
-  - name: wine-win32
-    config-opts:
-      - --disable-win64
-      - --disable-win16
-      - --disable-tests
-      - --with-x
-      - --with-ldap
-      - --with-netapi
-      - --without-cups
-      - --without-curses
-      - --without-capi
-      - --without-glu
-      - --without-gphoto
-      - --without-gsm
-      - --without-hal
-      - --without-opencl
-      - --without-pcap
-      - --without-udev
-    cleanup:
-      - /app/wine/app/wine/share/man
-      - /app/wine/share/applications
-    sources:
-      - type: archive
-        url: https://dl.winehq.org/wine/source/3.x/wine-3.18.tar.xz
-        sha256: 9be8d44b1b22814c76e6214fe8ce657ae90a7a17879e5cd2b2a87ad6a1391a77
+- name: scripts
+  buildsystem: simple
+  build-commands:
+  - install -d /app/bin
+  - install start /app/bin
+  - install installer /app/bin
+  sources:
+  - type: script
+    dest-filename: installer
+    commands:
+    - mkdir -p /var/data/win32
+    - wineboot
+    -
+    - # order user to wait
+    - winetricks dotnet40 | tee /tmp/dotnet.log | zenity --progress --pulsate --auto-close --auto-kill --no-cancel --text="Installing .net."
+    - winetricks gdiplus | tee /tmp/gdiplus.log | zenity --progress --pulsate --auto-close --auto-kill --no-cancel --text="Installing gdiplus."
+    - winetricks cjkfonts | tee /tmp/cjkfonts.log | zenity --progress --pulsate --auto-close --auto-kill --no-cancel --text="Installing fonts. Osu should start automatically."
+    -
+    - install -Dm644 /app/discord-rpc.dll "${WINEPREFIX}/drive_c/users/$USER/Local Settings/Application Data/osu!/discord-rpc.dll"
+    -
+    - # use win8.1 for wintab api
+    - wine reg add 'HKEY_CURRENT_USER\Software\Wine' /v Version /d win81 /f
+    -
+    - # osu installer complains about read only filesystem so we can copy it to /tmp
+    - cp /app/extra/osu!install.exe /tmp
+    - wine /tmp/osu!install.exe
 
+  - type: script
+    dest-filename: start
+    commands:
+    - # if osu doesn't exist then install
+    - if [[ ! -e "${WINEPREFIX}/drive_c/users/$USER/Local Settings/Application Data/osu!/osu!.exe" ]] ; then
+    - '    source /app/bin/installer'
+    - '    if [[ $? != 0 ]] ; then'
+    - '        echo "Installation failed, abort."'
+    - '        exit 1'
+    - '    fi'
+    - else
+    -      # if arguments exist then let wine handle them, otherwise just launch osu
+    -      if [[ $# == 0 ]] ; then
+    -           wine "C:/users/$USER/Local Settings/Application Data/osu!/osu!.exe"
+    -      else
+    -           wine start /ProgIDOpen osu! "$@"
+    -      fi
+    - fi
 
-  - name: scripts
-    buildsystem: simple
-    build-commands:
-      - install -d /app/bin
-      - install start /app/bin
-      - install installer /app/bin
+- name: fix
+  buildsystem: simple
+  build-commands:
+  - install -Dm644 linux-discord-rpc.dll /app/discord-rpc.dll
+  sources:
+  - type: file
+    url: https://github.com/goeo-/discord-rpc/releases/download/v3.2.0/linux-discord-rpc.dll
+    sha256: 216bed4c3f79375a6389779b9087ed18d9dae95304362dd21bf9f406cf3e49eb
 
-    sources:
-      - type: script
-        dest-filename: installer
-        commands:
-          - mkdir -p /var/data/win32
-          - wineboot
-          -
-          - # order user to wait
-          - winetricks dotnet40 | tee /tmp/dotnet.log | zenity --progress --pulsate --auto-close --auto-kill --no-cancel --text="Installing .net."
-          - winetricks gdiplus | tee /tmp/gdiplus.log | zenity --progress --pulsate --auto-close --auto-kill --no-cancel --text="Installing gdiplus."
-          - winetricks cjkfonts | tee /tmp/cjkfonts.log | zenity --progress --pulsate --auto-close --auto-kill --no-cancel --text="Installing fonts. Osu should start automatically."
-          -
-          - install -Dm644 /app/discord-rpc.dll "${WINEPREFIX}/drive_c/users/$USER/Local Settings/Application Data/osu!/discord-rpc.dll"
-          -
-          - # use win8.1 for wintab api
-          - wine reg add 'HKEY_CURRENT_USER\Software\Wine' /v Version /d win81 /f
-          -
-          - # osu installer complains about read only filesystem so we can copy it to /tmp
-          - cp /app/extra/osu!install.exe /tmp
-          - wine /tmp/osu!install.exe
-
-      - type: script
-        dest-filename: start
-        commands:
-          - # if osu doesn't exist then install
-          - if ! [ -e "${WINEPREFIX}/drive_c/users/$USER/Local Settings/Application Data/osu!/osu!.exe" ] ; then
-          - '    source /app/bin/installer'
-          - '    if [[ $? != 0 ]] ; then'
-          - '        echo "Installation failed, abort."'
-          - '        exit 1'
-          - '    fi'
-          - else
-          -      # if arguments exist then let wine handle them, otherwise just launch osu
-          -      if [ $# == 0 ] ; then
-          -           wine "C:/users/$USER/Local Settings/Application Data/osu!/osu!.exe"
-          -      else
-          -           wine start /ProgIDOpen osu! "$@"
-          -      fi
-          - fi
-
-
-  - name: resources
-    buildsystem: simple
-    build-commands:
-      - install -Dm644 sh.ppy.Osu.svg /app/share/icons/hicolor/512x512/apps/sh.ppy.Osu.svg
-      - install -Dm644 sh.ppy.Osu.appdata.xml /app/share/appdata/sh.ppy.Osu.appdata.xml
-      - install -Dm644 sh.ppy.Osu.desktop /app/share/applications/sh.ppy.Osu.desktop
-      - install -Dm644 linux-discord-rpc.dll /app/discord-rpc.dll
-
-    sources:
-      - type: file
-        path: sh.ppy.Osu.svg
-
-      - type: file
-        path: sh.ppy.Osu.appdata.xml
-
-      - type: file
-        path: sh.ppy.Osu.desktop
-
-      - type: file
-        url: https://github.com/goeo-/discord-rpc/releases/download/v3.2.0/linux-discord-rpc.dll
-        sha256: 216bed4c3f79375a6389779b9087ed18d9dae95304362dd21bf9f406cf3e49eb
+- name: resources
+  buildsystem: simple
+  build-commands:
+  - install -Dm644 sh.ppy.Osu.svg /app/share/icons/hicolor/512x512/apps/sh.ppy.Osu.svg
+  - install -Dm644 sh.ppy.Osu.appdata.xml /app/share/appdata/sh.ppy.Osu.appdata.xml
+  - install -Dm644 sh.ppy.Osu.desktop /app/share/applications/sh.ppy.Osu.desktop
+  sources:
+  - type: file
+    path: sh.ppy.Osu.svg
+  - type: file
+    path: sh.ppy.Osu.appdata.xml
+  - type: file
+    path: sh.ppy.Osu.desktop
